# Generated by Django 4.2.1 on 2023-05-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('annual_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=3)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_document.year')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_document.year')),
            ],
        ),
    ]
