# Generated by Django 4.2.1 on 2023-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytemperature',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='seasonaltemperature',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='annual_temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
