# Generated by Django 4.2.1 on 2023-05-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_document', '0002_alter_monthlytemperature_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='parameter',
            field=models.PositiveIntegerField(choices=[(1, 'MAX_TEMP'), (2, 'MIN_TEMP'), (3, 'MEAN_TEMP'), (4, 'SUNSHINE'), (5, 'RAIN_DAYS_GREATER_OR_EQUAL_TO_1_MM'), (6, 'DAYS_OF_AIR_FROST')], default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='year',
            name='region',
            field=models.PositiveIntegerField(choices=[(1, 'UK'), (2, 'ENGLAND'), (3, 'ENGLAND_N'), (4, 'ENGLAND_S'), (5, 'ENGLAND_E_AND_NE'), (6, 'ENGLAND_NW_OR_WALES_N'), (7, 'ENGLAND_SW_OR_WALES_S'), (8, 'ENGLAND_SE_OR_CENTRAL_S'), (9, 'WALES'), (10, 'SCOTLAND'), (11, 'SCOTLAND_N'), (12, 'SCOTLAND_E'), (13, 'SCOTLAND_W'), (14, 'NOTHERN_IRELAND'), (15, 'MIDLANDS'), (16, 'EAST_ANGLIA')], default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
